export enum TripStatus {
  REQUESTED = 'REQUESTED',
  OFFERED = 'OFFERED',
  ASSIGNED = 'ASSIGNED',
  PICKUP_STARTED = 'PICKUP_STARTED',
  IN_PROGRESS = 'IN_PROGRESS',
  COMPLETED = 'COMPLETED',
  PAID = 'PAID',
  CANCELED = 'CANCELED',
}
